[package]
name = "rtc-r"
version = "0.1.0"
edition = "2021"

[dependencies]
rfc5766-turn-server = "0.1"
warp = "0.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"